### ISSUE TITLE
runtime error: invalid memory address or nil pointer dereference when running GetStream

### ISSUE THREAD

**Issue by eyalgolan** [kkdai/youtube#250] opened 2022-05-26 11:17 UTC
GetStream fails (worked yesterday evening).

The issue seems to be related with the goja package as I am getting the following: `[panic]:\ngithub.com/dop251/goja.(*Runtime).toReflectValue`

stacktrace:
```
github.com/dop251/goja.(*Runtime).toReflectValue
        /home/eyal/projects/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220516123900-4418d4575a41/runtime.go:1945
    github.com/dop251/goja.(*Runtime).ExportTo
        /home/eyal/projects/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220516123900-4418d4575a41/runtime.go:2217
    github.com/kkdai/youtube/v2.evalJavascript
        /home/eyal/projects/go/pkg/mod/github.com/kkdai/youtube/v2@v2.7.14/decipher.go:138
    github.com/kkdai/youtube/v2.playerConfig.decodeNsig
        /home/eyal/projects/go/pkg/mod/github.com/kkdai/youtube/v2@v2.7.14/decipher.go:125
    github.com/kkdai/youtube/v2.(*Client).decryptNParam
        /home/eyal/projects/go/pkg/mod/github.com/kkdai/youtube/v2@v2.7.14/decipher.go:75
    github.com/kkdai/youtube/v2.(*Client).unThrottle
        /home/eyal/projects/go/pkg/mod/github.com/kkdai/youtube/v2@v2.7.14/decipher.go:62
    github.com/kkdai/youtube/v2.(*Client).GetStreamURLContext
        /home/eyal/projects/go/pkg/mod/github.com/kkdai/youtube/v2@v2.7.14/client.go:321
    github.com/kkdai/youtube/v2.(*Client).GetStreamURL
        /home/eyal/projects/go/pkg/mod/github.com/kkdai/youtube/v2@v2.7.14/client.go:315
    github.com/kkdai/youtube/v2.(*Client).GetStreamContext
        /home/eyal/projects/go/pkg/mod/github.com/kkdai/youtube/v2@v2.7.14/client.go:228
    github.com/kkdai/youtube/v2.(*Client).GetStream
```

**Comment by choonsiong** [comment] 2022-05-26 11:26
Same here:


```
19:16:50 219 bin took 4s ➜ ./youtubedr download 'https://www.youtube.com/watch?v=MeaW1QRugFk'
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x14803de]

goroutine 1 [running]:
github.com/dop251/goja.(*Runtime).toReflectValue(0xc00028ae00, {0x0?, 0x0?}, {0x15fde40?, 0xc000286120?, 0xc000286120?}, 0xc000286148)
	/Users/lcs/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220214123719-b09a6bfa842f/runtime.go:1925 +0x23e
github.com/dop251/goja.(*Runtime).ExportTo(0xc00028ae00?, {0x0, 0x0}, {0x15e0fa0?, 0xc000286120?})
	/Users/lcs/go/pkg/mod/github.com/dop251/goja@v0.0.0-20220214123719-b09a6bfa842f/runtime.go:2197 +0x185
github.com/kkdai/youtube/v2.evalJavascript({0xc0000ea900, 0x812}, {0xc0004f058c, 0x10})
	/Users/lcs/Developer/personal/youtube/decipher.go:138 +0xcc
github.com/kkdai/youtube/v2.playerConfig.decodeNsig({0xc000ba4000?, 0xc000284f00?, 0x17a98a4?}, {0xc0004f058c, 0x10})
	/Users/lcs/Developer/personal/youtube/decipher.go:125 +0x4a
github.com/kkdai/youtube/v2.(*Client).decryptNParam(0xc0001a6de0, {0x0?, 0xc0000e64f6?}, {0xc000ba4000?, 0x1d156d?, 0x218000?}, 0xc000284f00)
	/Users/lcs/Developer/personal/youtube/decipher.go:75 +0x11d
github.com/kkdai/youtube/v2.(*Client).decipherURL(0x8?, {0x17b4138, 0xc000036080}, {0x7ff7bfeff8f5, 0xb}, {0xc0000e6480, 0x471})
	/Users/lcs/Developer/personal/youtube/decipher.go:40 +0x33a
github.com/kkdai/youtube/v2.(*Client).GetStreamURLContext(0x203000?, {0x17b4138?, 0xc000036080?}, 0x106196e?, 0x1019c28?)
	/Users/lcs/Developer/personal/youtube/client.go:329 +0x4b
github.com/kkdai/youtube/v2.(*Client).GetStreamURL(...)
	/Users/lcs/Developer/personal/youtube/client.go:315
github.com/kkdai/youtube/v2.(*Client).GetStreamContext(0xc0001a6de0, {0x17b4138, 0xc000036080}, 0x0?, 0xc0000003c0)
	/Users/lcs/Developer/personal/youtube/client.go:228 +0x5c
github.com/kkdai/youtube/v2/downloader.(*Downloader).videoDLWorker(0xc000042540?, {0x17b4138?, 0xc000036080?}, 0xc000286300, 0x100e765?, 0x90?)
	/Users/lcs/Developer/personal/youtube/downloader/downloader.go:153 +0x4e
github.com/kkdai/youtube/v2/downloader.(*Downloader).Download(0xc0001a6de0, {0x17b4138, 0xc000036080}, 0xc00038c000, 0xc0000003c0, {0x0, 0x0})
	/Users/lcs/Developer/personal/youtube/downloader/downloader.go:56 +0x25f
main.download({0x7ff7bfeff8d5?, 0x0?})
	/Users/lcs/Developer/personal/youtube/cmd/youtubedr/download.go:54 +0x170
main.glob..func1(0x1cf0f00?, {0xc00007dec0?, 0x1?, 0x1?})
	/Users/lcs/Developer/personal/youtube/cmd/youtubedr/download.go:20 +0x2a
github.com/spf13/cobra.(*Command).execute(0x1cf0f00, {0xc00007dea0, 0x1, 0x1})
	/Users/lcs/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x663
github.com/spf13/cobra.(*Command).ExecuteC(0x1cf1180)
	/Users/lcs/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x3b4
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/lcs/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
main.main()
	/Users/lcs/Developer/personal/youtube/cmd/youtubedr/main.go:9 +0x25
19:17:00 219 bin took 4s ❯
```

**Comment by choonsiong** [comment] 2022-05-26 11:30
I added back the '=' and now it works:

```
19:28:51 219 youtube on  master +1 -1 ➜ go build ./cmd/youtubedr 
19:28:57 219 youtube on  master +1 -1 took 2s ➜ ./youtubedr download 'https://www.youtube.com/watch?v=MeaW1QRugFk'                             
192.36 MiB / 192.36 MiB 100 % [==============================================================] 0s ] 4.27 MiB/s
19:29:59 219 youtube on  master +1 -1 took 56s ➜ diff decipher.go decipher.go.orig 
132c132
< 	_, err := vm.RunString(myName + "=" + jsFunction)
---
> 	_, err := vm.RunString(myName + jsFunction)
19:30:10 219 youtube on  master +1 -1 ❯
```

**Comment by eyalgolan** [comment] 2022-05-26 12:13
Following @choonsiong solution, seems that the last commit need to be reverted.

**Comment by Jafter** [comment] 2022-05-26 16:54
> I added back the '=' and now it works:
> 
> ```
> 19:28:51 219 youtube on  master +1 -1 ➜ go build ./cmd/youtubedr 
> 19:28:57 219 youtube on  master +1 -1 took 2s ➜ ./youtubedr download 'https://www.youtube.com/watch?v=MeaW1QRugFk'                             
> 192.36 MiB / 192.36 MiB 100 % [==============================================================] 0s ] 4.27 MiB/s
> 19:29:59 219 youtube on  master +1 -1 took 56s ➜ diff decipher.go decipher.go.orig 
> 132c132
> < 	_, err := vm.RunString(myName + "=" + jsFunction)
> ---
> > 	_, err := vm.RunString(myName + jsFunction)
> 19:30:10 219 youtube on  master +1 -1 ❯
> ```

Strange that yesterday it complained about it because it already had the = in it, causing a similar problem...

**Comment by choonsiong** [comment] 2022-05-27 06:51
> > I added back the '=' and now it works:
> > ```
> > 19:28:51 219 youtube on  master +1 -1 ➜ go build ./cmd/youtubedr 
> > 19:28:57 219 youtube on  master +1 -1 took 2s ➜ ./youtubedr download 'https://www.youtube.com/watch?v=MeaW1QRugFk'                             
> > 192.36 MiB / 192.36 MiB 100 % [==============================================================] 0s ] 4.27 MiB/s
> > 19:29:59 219 youtube on  master +1 -1 took 56s ➜ diff decipher.go decipher.go.orig 
> > 132c132
> > < 	_, err := vm.RunString(myName + "=" + jsFunction)
> > ---
> > > 	_, err := vm.RunString(myName + jsFunction)
> > 19:30:10 219 youtube on  master +1 -1 ❯
> > ```
> 
> Strange that yesterday it complained about it because it already had the = in it, causing a similar problem...

Indeed, probably need help from other who is more familiar with the codebase to check the reason of previous error.

**Comment by corny** [comment] 2022-05-28 09:19
I've created the [fix-decipher](https://github.com/kkdai/youtube/tree/fix-decipher) branch that stores artifacts for debugging purposes. Unfortunately I am not able to reproduce the issue at the moment.

Please check out the branch and run `make test-integration`. Does anything fail?

**Comment by choonsiong** [comment] 2022-05-28 11:50
> I've created the [fix-decipher](https://github.com/kkdai/youtube/tree/fix-decipher) branch that stores artifacts for debugging purposes. Unfortunately I am not able to reproduce the issue at the moment.
> 
> Please check out the branch and run `make test-integration`. Does anything fail?

Looks fine

```
19:47:53 217 youtube on  HEAD took 24s ➜ git branch
* (HEAD detached at origin/fix-decipher)
  master
19:48:25 217 youtube on  HEAD ➜ make test-integration
mkdir -p output
rm -f output/*
ARTIFACTS=output go test -race -covermode=atomic -coverprofile=coverage.out -tags=integration ./...
ok  	github.com/kkdai/youtube/v2	20.968s	coverage: 79.3% of statements
?   	github.com/kkdai/youtube/v2/cmd/youtubedr	[no test files]
ok  	github.com/kkdai/youtube/v2/downloader	5.046s	coverage: 85.0% of statements
19:48:51 217 youtube on  HEAD took 22s
```

**Comment by corny** [comment] 2022-05-29 08:58
I've just merged it into master.

**Closed by corny** 2022-05-29 08:58 UTC
